//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingMst
    {
        public int Id { get; set; }
        public Nullable<int> GrpMemberId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> VoteId { get; set; }
    }
}
